name: Initialize branches

on: [push]

jobs:
  initialize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: initialize {x86_64,aarch64,i686} branches
        run: |
          set -ex

          for arch in x86_64 aarch64 i686
          do
            git switch --orphan $arch

            base_url=https://wingit.blob.core.windows.net/$arch
            case "$arch" in
              x86_64)
                base_url=https://wingit.blob.core.windows.net/x86-64
                msystem=mingw64
                ;;
              aarch64)
                msystem=clangarm64
                ;;
              i686)
                msystem=mingw32
                ;;
            esac

            date="$(curl --head $base_url/git-for-windows.db |sed -n 's/^Last-Modified: //ip')"
            test -n "$date" || exit 1

            for suffix in '' "-$msystem"
            do
              for infix in db files
              do
                for ext in '' .tar.xz
                do
                  for sig in '' .sig
                  do
                    name=git-for-windows$suffix.$infix$ext$sig
                    echo "::notice::Downloading $name"
                    curl -fLo $name $base_url/$name &&
                    git add $name || exit 1
                  done
                done
              done
            done
            
            for package in $(tar --wildcards -Oxvf git-for-windows.db \*/desc 2>&1 |
              sed -n '/%FILENAME%/{n;p}')
            do
              for sig in '' .sig
              do
                name=$package$sig
                echo "::notice::Downloading $name"
                curl -fLo $name $base_url/$name &&
                git add $name || exit 1
              done
            done

            git \
              -c user.name='${{ github.actor }}' \
              -c user.email='${{ github.actor }}@users.noreply.github.com' \
              commit -m "Initialize $arch" --date="$date" || exit 1

            git push origin HEAD || exit 1
          done
